"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight } from "lucide-react";
import { Header, Ornaments, Panel, Field, Button, Notice } from "@/components/ui";
import { api } from "@/components/project-context";
import type { ProjectData } from "@/lib/types";
export default function Reflection() {
  const [data, setData] = useState<ProjectData | null>(null); const [body, setBody] = useState(""); const [saved, setSaved] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const router = useRouter();
  useEffect(() => { void (async () => { try { const r = await fetch("/api/studio"); const d = await r.json(); if (r.status === 401) { router.replace("/join"); return; } if (!r.ok) throw new Error(d.error); if (d.session.role === "teacher") { router.replace("/teacher"); return; } setData(d); const item = await fetch("/api/studio?reflection=1"); const reflection = await item.json(); if (!item.ok) throw new Error(reflection.error); const backup = sessionStorage.getItem(`int6066-reflection:${d.session.memberId}`); setBody(backup ?? reflection.body); } catch (e) { setError((e as Error).message); } })(); }, [router]);
  async function save(e: React.FormEvent) { e.preventDefault(); if (!body.trim()) { setError("Write a reflection before saving. This journal is optional for today’s Empathize and Define steps."); return; } setBusy(true); try { await api("reflection", { body }); setSaved(true); setError(""); sessionStorage.removeItem(`int6066-reflection:${data?.session.memberId}`); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <div className="page"><Ornaments /><Header active="reflection" groupName={data?.group.name} members={data?.group.members} name={data?.session.name} /><main id="main" className="reflection-main"><p className="eyebrow">YOUR INDIVIDUAL LEARNING JOURNEY</p><h1>Notice how your<br />thinking changes.</h1><p className="subtitle">A personal record alongside your group’s design process.</p>{error ? <Notice error>{error}</Notice> : null}<div className="two-columns"><Panel title="My reflection"><form onSubmit={save}><Field label="What have you learned about innovative learning environments?" hint="Optional for today’s learning path. Write some text when you choose to save a reflection."><textarea rows={13} maxLength={12000} value={body} onChange={e => { setBody(e.target.value); setSaved(false); if (data) sessionStorage.setItem(`int6066-reflection:${data.session.memberId}`, e.target.value); }} placeholder="How did starting with learners change your understanding? What surprised you? What do you want to investigate next?" /></Field><Button disabled={busy || !data || !body.trim()}>{busy ? "Saving…" : "Save my reflection"}<ArrowRight size={17} /></Button>{saved ? <Notice>Your personal reflection is saved.</Notice> : null}</form></Panel><Panel title="Prompts for your next reflection"><ul className="reflection-prompts"><li>Which observation changed your view of the learner?</li><li>What assumption did your group question?</li><li>How does your problem connect to learning, rather than only to technology?</li><li>What still needs to be understood before designing a solution?</li><li>How did your own contribution shape the group’s thinking?</li></ul><p className="muted">Use this as a course journal. Your final course reflection can later take the form of an innovative digital artefact.</p></Panel></div></main></div>;
}
